name: Reuse other workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yaml
    with:
      who: '@Bottle7'
    
  use-output:
    runs-on: ubuntu-latest
    needs: call-workflow
    steps:
      - run: |
          echo "The previous job was called at ${{ needs.call-workflow.outputs.current-time }}
