name: Reusable workflow

on:
  workflow_call:
    inputs:
      who:
        description: 'The person to greet'
        type: string
        required: true
        default: World
    outputs:
      current-time: 
        description: "The time in which the workflow is called"
        value: ${{ jobs.reusable-job.outputs.current-time }}
        
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.time }}
    steps:
      - name: Greeting
        run: |
          echo "Hello, ${{ inputs.who }}!"
      - name: Time
        id: time
        run: |
          echo "time=$(date)" >> $GITHUB_OUTPUT
          
